
    import React from 'react';
    import ApgIcon from '@apg.gg/icons/lib/ApgIcon';
import ArrowDownIcon from '@apg.gg/icons/lib/ArrowDownIcon';
import ArrowLeftIcon from '@apg.gg/icons/lib/ArrowLeftIcon';
import ArrowRightIcon from '@apg.gg/icons/lib/ArrowRightIcon';
import ArrowUpIcon from '@apg.gg/icons/lib/ArrowUpIcon';
import CommentIcon from '@apg.gg/icons/lib/CommentIcon';
import DiscordIcon from '@apg.gg/icons/lib/DiscordIcon';
import ErrorIcon from '@apg.gg/icons/lib/ErrorIcon';
import FacebookIcon from '@apg.gg/icons/lib/FacebookIcon';
import GoogleIcon from '@apg.gg/icons/lib/GoogleIcon';
import HeartIcon from '@apg.gg/icons/lib/HeartIcon';
import IconApgLogo from '@apg.gg/icons/lib/IconApgLogo';
import IconApgLogoFull from '@apg.gg/icons/lib/IconApgLogoFull';
import IconBaron from '@apg.gg/icons/lib/IconBaron';
import IconDrake from '@apg.gg/icons/lib/IconDrake';
import IconDrakeCloud from '@apg.gg/icons/lib/IconDrakeCloud';
import IconDrakeInfernal from '@apg.gg/icons/lib/IconDrakeInfernal';
import IconDrakeMountain from '@apg.gg/icons/lib/IconDrakeMountain';
import IconDrakeOcean from '@apg.gg/icons/lib/IconDrakeOcean';
import IconFirstBlood from '@apg.gg/icons/lib/IconFirstBlood';
import IconHamburger from '@apg.gg/icons/lib/IconHamburger';
import IconHerald from '@apg.gg/icons/lib/IconHerald';
import IconKills from '@apg.gg/icons/lib/IconKills';
import IconLaneBottom from '@apg.gg/icons/lib/IconLaneBottom';
import IconLaneJungle from '@apg.gg/icons/lib/IconLaneJungle';
import IconLaneMid from '@apg.gg/icons/lib/IconLaneMid';
import IconLaneSupport from '@apg.gg/icons/lib/IconLaneSupport';
import IconLaneTop from '@apg.gg/icons/lib/IconLaneTop';
import IconLogout from '@apg.gg/icons/lib/IconLogout';
import IconSettings from '@apg.gg/icons/lib/IconSettings';
import IconTurret from '@apg.gg/icons/lib/IconTurret';
import IconTurretBlue from '@apg.gg/icons/lib/IconTurretBlue';
import IconTurretRed from '@apg.gg/icons/lib/IconTurretRed';
import IconWildRiftLogo from '@apg.gg/icons/lib/IconWildRiftLogo';
import InstagramIcon from '@apg.gg/icons/lib/InstagramIcon';
import MenuIcon from '@apg.gg/icons/lib/MenuIcon';
import MenuOpenIcon from '@apg.gg/icons/lib/MenuOpenIcon';
import MoreVerticalIcon from '@apg.gg/icons/lib/MoreVerticalIcon';
import NavigateNextIcon from '@apg.gg/icons/lib/NavigateNextIcon';
import NavigatePrevIcon from '@apg.gg/icons/lib/NavigatePrevIcon';
import PersonIcon from '@apg.gg/icons/lib/PersonIcon';
import PlusIcon from '@apg.gg/icons/lib/PlusIcon';
import SearchIcon from '@apg.gg/icons/lib/SearchIcon';
import ShareIcon from '@apg.gg/icons/lib/ShareIcon';
import TelegramIcon from '@apg.gg/icons/lib/TelegramIcon';
import TiktokIcon from '@apg.gg/icons/lib/TiktokIcon';
import TwitchIcon from '@apg.gg/icons/lib/TwitchIcon';
import TwitterIcon from '@apg.gg/icons/lib/TwitterIcon';
import VerifiedIcon from '@apg.gg/icons/lib/VerifiedIcon';
import VisibilityIcon from '@apg.gg/icons/lib/VisibilityIcon';
import VisibilityOffIcon from '@apg.gg/icons/lib/VisibilityOffIcon';
import XCircleIcon from '@apg.gg/icons/lib/XCircleIcon';
import XIcon from '@apg.gg/icons/lib/XIcon';

    function getComponentByName(name: string, className: string) {
      switch (name) {
        case "apg": return <ApgIcon className={className} />;
case "arrowDown": return <ArrowDownIcon className={className} />;
case "arrowLeft": return <ArrowLeftIcon className={className} />;
case "arrowRight": return <ArrowRightIcon className={className} />;
case "arrowUp": return <ArrowUpIcon className={className} />;
case "comment": return <CommentIcon className={className} />;
case "discord": return <DiscordIcon className={className} />;
case "error": return <ErrorIcon className={className} />;
case "facebook": return <FacebookIcon className={className} />;
case "google": return <GoogleIcon className={className} />;
case "heart": return <HeartIcon className={className} />;
case "apgLogo": return <IconApgLogo className={className} />;
case "apgLogoFull": return <IconApgLogoFull className={className} />;
case "baron": return <IconBaron className={className} />;
case "drake": return <IconDrake className={className} />;
case "drakeCloud": return <IconDrakeCloud className={className} />;
case "drakeInfernal": return <IconDrakeInfernal className={className} />;
case "drakeMountain": return <IconDrakeMountain className={className} />;
case "drakeOcean": return <IconDrakeOcean className={className} />;
case "firstBlood": return <IconFirstBlood className={className} />;
case "hamburger": return <IconHamburger className={className} />;
case "herald": return <IconHerald className={className} />;
case "kills": return <IconKills className={className} />;
case "laneBottom": return <IconLaneBottom className={className} />;
case "laneJungle": return <IconLaneJungle className={className} />;
case "laneMid": return <IconLaneMid className={className} />;
case "laneSupport": return <IconLaneSupport className={className} />;
case "laneTop": return <IconLaneTop className={className} />;
case "logout": return <IconLogout className={className} />;
case "settings": return <IconSettings className={className} />;
case "turret": return <IconTurret className={className} />;
case "turretBlue": return <IconTurretBlue className={className} />;
case "turretRed": return <IconTurretRed className={className} />;
case "wildRiftLogo": return <IconWildRiftLogo className={className} />;
case "instagram": return <InstagramIcon className={className} />;
case "menu": return <MenuIcon className={className} />;
case "menuOpen": return <MenuOpenIcon className={className} />;
case "moreVertical": return <MoreVerticalIcon className={className} />;
case "navigateNext": return <NavigateNextIcon className={className} />;
case "navigatePrev": return <NavigatePrevIcon className={className} />;
case "person": return <PersonIcon className={className} />;
case "plus": return <PlusIcon className={className} />;
case "search": return <SearchIcon className={className} />;
case "share": return <ShareIcon className={className} />;
case "telegram": return <TelegramIcon className={className} />;
case "tiktok": return <TiktokIcon className={className} />;
case "twitch": return <TwitchIcon className={className} />;
case "twitter": return <TwitterIcon className={className} />;
case "verified": return <VerifiedIcon className={className} />;
case "visibility": return <VisibilityIcon className={className} />;
case "visibilityOff": return <VisibilityOffIcon className={className} />;
case "xCircle": return <XCircleIcon className={className} />;
case "x": return <XIcon className={className} />;
        default: return null;
      }
    }

    export default getComponentByName;
  