const path = require("path");

const SRC_DIR = path.resolve("src");

module.exports = {
  // Icons
  IconApgLogo: path.resolve(SRC_DIR, "IconApgLogo"),
  IconBaron: path.resolve(SRC_DIR, "IconBaron"),
  IconDrake: path.resolve(SRC_DIR, "IconDrake"),
  IconDrakeCloud: path.resolve(SRC_DIR, "IconDrakeCloud"),
  IconDrakeInfernal: path.resolve(SRC_DIR, "IconDrakeInfernal"),
  IconDrakeMountain: path.resolve(SRC_DIR, "IconDrakeMountain"),
  IconDrakeOcean: path.resolve(SRC_DIR, "IconDrakeOcean"),
  IconFirstBlood: path.resolve(SRC_DIR, "IconFirstBlood"),
  IconHerald: path.resolve(SRC_DIR, "IconHerald"),
  IconKills: path.resolve(SRC_DIR, "IconKills"),
  IconLaneBottom: path.resolve(SRC_DIR, "IconLaneBottom"),
  IconLaneJungle: path.resolve(SRC_DIR, "IconLaneJungle"),
  IconLaneMid: path.resolve(SRC_DIR, "IconLaneMid"),
  IconLaneSupport: path.resolve(SRC_DIR, "IconLaneSupport"),
  IconLaneTop: path.resolve(SRC_DIR, "IconLaneTop"),
  IconTurret: path.resolve(SRC_DIR, "IconTurret"),
  IconTurretBlue: path.resolve(SRC_DIR, "IconTurretBlue"),
  IconTurretRed: path.resolve(SRC_DIR, "IconTurretRed"),
  IconTwitter: path.resolve(SRC_DIR, "IconTwitter"),
  IconDiscord: path.resolve(SRC_DIR, "IconDiscord"),
  IconWildRiftLogo: path.resolve(SRC_DIR, "IconWildRiftLogo"),
  IconApgLogoFull: path.resolve(SRC_DIR, "IconApgLogoFull"),
  IconSettings: path.resolve(SRC_DIR, "IconSettings"),
  IconLogout: path.resolve(SRC_DIR, "IconLogout"),
  IconHamburger: path.resolve(SRC_DIR, "IconHamburger"),
  // New icons
  ApgIcon: path.resolve(SRC_DIR, "ApgIcon"),
  ArrowDownIcon: path.resolve(SRC_DIR, "ArrowDownIcon"),
  ArrowLeftIcon: path.resolve(SRC_DIR, "ArrowLeftIcon"),
  ArrowRightIcon: path.resolve(SRC_DIR, "ArrowRightIcon"),
  ArrowUpIcon: path.resolve(SRC_DIR, "ArrowUpIcon"),
  VerifiedIcon: path.resolve(SRC_DIR, "VerifiedIcon"),
  CommentIcon: path.resolve(SRC_DIR, "CommentIcon"),
  ErrorIcon: path.resolve(SRC_DIR, "ErrorIcon"),
  HeartIcon: path.resolve(SRC_DIR, "HeartIcon"),
  MenuIcon: path.resolve(SRC_DIR, "MenuIcon"),
  MenuOpenIcon: path.resolve(SRC_DIR, "MenuOpenIcon"),
  MoreVerticalIcon: path.resolve(SRC_DIR, "MoreVerticalIcon"),
  PersonIcon: path.resolve(SRC_DIR, "PersonIcon"),
  PlusIcon: path.resolve(SRC_DIR, "PlusIcon"),
  SearchIcon: path.resolve(SRC_DIR, "SearchIcon"),
  ShareIcon: path.resolve(SRC_DIR, "ShareIcon"),
  VisibilityIcon: path.resolve(SRC_DIR, "VisibilityIcon"),
  VisibilityOffIcon: path.resolve(SRC_DIR, "VisibilityOffIcon"),
  XCircleIcon: path.resolve(SRC_DIR, "XCircleIcon"),
  XIcon: path.resolve(SRC_DIR, "XIcon"),
  // Social icons
  FacebookIcon: path.resolve(SRC_DIR, "FacebookIcon"),
  GoogleIcon: path.resolve(SRC_DIR, "GoogleIcon"),
  InstagramIcon: path.resolve(SRC_DIR, "InstagramIcon"),
  TelegramIcon: path.resolve(SRC_DIR, "TelegramIcon"),
  TiktokIcon: path.resolve(SRC_DIR, "TiktokIcon"),
  TwitchIcon: path.resolve(SRC_DIR, "TwitchIcon"),
};
