name: Server CI workflow

on:
  push:
    branches: [ develop ]
    tags:
      - 'v*' 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v4.1.1

      - 
        name: Docker meta
        id: docker_meta
        uses: Synodic-Software/Tag-Metadata@v1.0.8
        
      - 
        name: Login to private registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - 
        name: Build and Push Docker Image
        uses: belon/docker-build-push@v4.0
        with:
          image: apg-cuk
          tags: latest, ${{ steps.docker_meta.outputs.tag }}
          dockerfile: ./Dockerfile
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}