name: Build and Deploy - Develop Branch

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to server and pull latest changes
        run: |
          ssh -o StrictHostKeyChecking=no root@85.239.242.71 "cd /home/apg-sdk && git checkout main && git pull"

      - name: Install and build storybook
        run: |
          ssh -o StrictHostKeyChecking=no root@85.239.242.71 "cd /home/apg-sdk && yarn install -W"
          ssh -o StrictHostKeyChecking=no root@85.239.242.71 "cd /home/apg-sdk && yarn add @apg.gg/core @apg.gg/icons -W"
          ssh -o StrictHostKeyChecking=no root@85.239.242.71 "cd /home/apg-sdk && yarn storybook:build"

      - name: Rebuild image
        run: |
          ssh -o StrictHostKeyChecking=no root@85.239.242.71 "cd /home/apg-sdk && docker build -t apg-cuk ."

      - name: Stop and remove existing container
        run: |
          ssh -o StrictHostKeyChecking=no root@85.239.242.71 "cd /home/apg-sdk && docker stop apg-cuk || true"
          ssh -o StrictHostKeyChecking=no root@85.239.242.71 "cd /home/apg-sdk && docker rm apg-cuk || true"

      - name: Build and run Docker containers
        run: |
          ssh -o StrictHostKeyChecking=no root@85.239.242.71 "cd /home/apg-sdk && docker-compose up -d --build"